// Shared player data structure across the application
export const playerDataByYear = {
  "2025": [
    {
      id: "tomi",
      name: "Tomi",
      avatar: "👤",
      position: "Forward",
      stats: { goals: 9, assists: 6, cleanSheets: 1, yellowCards: 2, redCards: 1, gamesPlayed: 15 },
      totalPoints: 42,
      rank: 1,
    },
    {
      id: "kunle",
      name: "Kunle",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 7, assists: 8, cleanSheets: 2, yellowCards: 3, redCards: 0, gamesPlayed: 16 },
      totalPoints: 38,
      rank: 2,
    },
    {
      id: "mayowa",
      name: "Mayowa",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 5, assists: 5, cleanSheets: 0, yellowCards: 1, redCards: 0, gamesPlayed: 14 },
      totalPoints: 28,
      rank: 3,
    },
    {
      id: "gbaja",
      name: "Gbaja",
      avatar: "👤",
      position: "Forward",
      stats: { goals: 6, assists: 2, cleanSheets: 0, yellowCards: 3, redCards: 0, gamesPlayed: 13 },
      totalPoints: 25,
      rank: 4,
    },
    {
      id: "ajegs",
      name: "Ajegs",
      avatar: "👤",
      position: "Goalkeeper",
      stats: { goals: 0, assists: 1, cleanSheets: 7, yellowCards: 1, redCards: 0, gamesPlayed: 16 },
      totalPoints: 23,
      rank: 5,
    },
    {
      id: "segun",
      name: "Segun",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 2, assists: 3, cleanSheets: 5, yellowCards: 2, redCards: 0, gamesPlayed: 15 },
      totalPoints: 22,
      rank: 6,
    },
    {
      id: "tobi",
      name: "Tobi",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 1, assists: 2, cleanSheets: 4, yellowCards: 1, redCards: 0, gamesPlayed: 12 },
      totalPoints: 18,
      rank: 7,
    },
    {
      id: "debo",
      name: "Debo",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 3, assists: 1, cleanSheets: 1, yellowCards: 5, redCards: 1, gamesPlayed: 14 },
      totalPoints: 15,
      rank: 8,
    },
    {
      id: "uzo",
      name: "Uzo",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 1, assists: 0, cleanSheets: 2, yellowCards: 4, redCards: 2, gamesPlayed: 11 },
      totalPoints: 8,
      rank: 9,
    },
  ],
  "2024": [
    {
      id: "tomi",
      name: "Tomi",
      avatar: "👤",
      position: "Forward",
      stats: {
        goals: 12,
        assists: 4,
        cleanSheets: 0,
        yellowCards: 3,
        redCards: 0,
        gamesPlayed: 18,
      },
      totalPoints: 48,
      rank: 1,
    },
    {
      id: "gbaja",
      name: "Gbaja",
      avatar: "👤",
      position: "Forward",
      stats: {
        goals: 10,
        assists: 3,
        cleanSheets: 1,
        yellowCards: 2,
        redCards: 1,
        gamesPlayed: 17,
      },
      totalPoints: 41,
      rank: 2,
    },
    {
      id: "kunle",
      name: "Kunle",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 8, assists: 7, cleanSheets: 3, yellowCards: 4, redCards: 0, gamesPlayed: 19 },
      totalPoints: 39,
      rank: 3,
    },
    {
      id: "mayowa",
      name: "Mayowa",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 6, assists: 6, cleanSheets: 2, yellowCards: 2, redCards: 0, gamesPlayed: 16 },
      totalPoints: 32,
      rank: 4,
    },
    {
      id: "ajegs",
      name: "Ajegs",
      avatar: "👤",
      position: "Goalkeeper",
      stats: { goals: 1, assists: 0, cleanSheets: 9, yellowCards: 0, redCards: 0, gamesPlayed: 18 },
      totalPoints: 28,
      rank: 5,
    },
    {
      id: "segun",
      name: "Segun",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 3, assists: 4, cleanSheets: 6, yellowCards: 3, redCards: 0, gamesPlayed: 17 },
      totalPoints: 27,
      rank: 6,
    },
    {
      id: "tobi",
      name: "Tobi",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 2, assists: 1, cleanSheets: 5, yellowCards: 1, redCards: 0, gamesPlayed: 15 },
      totalPoints: 21,
      rank: 7,
    },
    {
      id: "debo",
      name: "Debo",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 4, assists: 2, cleanSheets: 0, yellowCards: 6, redCards: 2, gamesPlayed: 16 },
      totalPoints: 18,
      rank: 8,
    },
    {
      id: "uzo",
      name: "Uzo",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 0, assists: 1, cleanSheets: 3, yellowCards: 5, redCards: 1, gamesPlayed: 13 },
      totalPoints: 9,
      rank: 9,
    },
  ],
  "2023": [
    {
      id: "kunle",
      name: "Kunle",
      avatar: "👤",
      position: "Midfielder",
      stats: {
        goals: 11,
        assists: 9,
        cleanSheets: 1,
        yellowCards: 2,
        redCards: 0,
        gamesPlayed: 20,
      },
      totalPoints: 51,
      rank: 1,
    },
    {
      id: "tomi",
      name: "Tomi",
      avatar: "👤",
      position: "Forward",
      stats: {
        goals: 14,
        assists: 2,
        cleanSheets: 0,
        yellowCards: 4,
        redCards: 1,
        gamesPlayed: 19,
      },
      totalPoints: 48,
      rank: 2,
    },
    {
      id: "mayowa",
      name: "Mayowa",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 7, assists: 8, cleanSheets: 1, yellowCards: 1, redCards: 0, gamesPlayed: 18 },
      totalPoints: 38,
      rank: 3,
    },
    {
      id: "gbaja",
      name: "Gbaja",
      avatar: "👤",
      position: "Forward",
      stats: { goals: 9, assists: 1, cleanSheets: 0, yellowCards: 3, redCards: 0, gamesPlayed: 16 },
      totalPoints: 31,
      rank: 4,
    },
    {
      id: "segun",
      name: "Segun",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 1, assists: 2, cleanSheets: 8, yellowCards: 1, redCards: 0, gamesPlayed: 19 },
      totalPoints: 27,
      rank: 5,
    },
    {
      id: "ajegs",
      name: "Ajegs",
      avatar: "👤",
      position: "Goalkeeper",
      stats: { goals: 0, assists: 0, cleanSheets: 8, yellowCards: 2, redCards: 0, gamesPlayed: 17 },
      totalPoints: 22,
      rank: 6,
    },
    {
      id: "tobi",
      name: "Tobi",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 0, assists: 3, cleanSheets: 6, yellowCards: 0, redCards: 0, gamesPlayed: 14 },
      totalPoints: 21,
      rank: 7,
    },
    {
      id: "debo",
      name: "Debo",
      avatar: "👤",
      position: "Midfielder",
      stats: { goals: 2, assists: 3, cleanSheets: 2, yellowCards: 7, redCards: 0, gamesPlayed: 17 },
      totalPoints: 18,
      rank: 8,
    },
    {
      id: "uzo",
      name: "Uzo",
      avatar: "👤",
      position: "Defender",
      stats: { goals: 2, assists: 0, cleanSheets: 4, yellowCards: 6, redCards: 3, gamesPlayed: 15 },
      totalPoints: 14,
      rank: 9,
    },
  ],
};

export type Player = (typeof playerDataByYear)["2025"][0];
export type PlayerStats = Player["stats"];
export type Position = Player["position"];
